name: MoreVanillaAdvancements
version: '${version}'
main: fr.mathilde.moreVanillaAdvancements.MoreVanillaAdvancements
api-version: '1.21'
authors:
  - Mathilde

commands:
  mva:
    description: Commandes principales pour MoreVanillaAdvancements
    usage: /mva [reload|open|list|reset|settings]
    aliases: [achievements, succes]
    permission: mva.use

permissions:
  mva.use:
    default: true
  mva.reload:
    default: op
  mva.reset:
    default: op
  mva.editor:
    default: op
  mva.editor.delete:
    default: op


softdepend:
  - PlaceholderAPI
